// <auto-generated />
using System;
using KLALIK.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KLALIK.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418204925_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KLALIK.Models.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.BalanceTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_balance_transactions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_balance_transactions_user_id");

                    b.ToTable("balance_transactions", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientUserId")
                        .HasColumnType("integer")
                        .HasColumnName("client_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("MasterProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("master_profile_id");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("queue_number");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("WorkshopServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_service_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("ClientUserId")
                        .HasDatabaseName("ix_bookings_client_user_id");

                    b.HasIndex("MasterProfileId")
                        .HasDatabaseName("ix_bookings_master_profile_id");

                    b.HasIndex("WorkshopServiceId")
                        .HasDatabaseName("ix_bookings_workshop_service_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.CollectionDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_collection_directions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_collection_directions_name");

                    b.ToTable("collection_directions", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.MasterProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QualificationLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("qualification_level_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_master_profiles");

                    b.HasIndex("QualificationLevelId")
                        .HasDatabaseName("ix_master_profiles_qualification_level_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_master_profiles_user_id");

                    b.ToTable("master_profiles", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.MasterServiceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("master_profile_id");

                    b.Property<int>("WorkshopServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_service_id");

                    b.HasKey("Id")
                        .HasName("pk_master_service_links");

                    b.HasIndex("WorkshopServiceId")
                        .HasDatabaseName("ix_master_service_links_workshop_service_id");

                    b.HasIndex("MasterProfileId", "WorkshopServiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_master_service_links_master_profile_id_workshop_service_id");

                    b.ToTable("master_service_links", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.QualificationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_qualification_levels");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_qualification_levels_sort_order");

                    b.ToTable("qualification_levels", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.QualificationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("MasterProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("master_profile_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<int?>("ResolverUserId")
                        .HasColumnType("integer")
                        .HasColumnName("resolver_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_qualification_requests");

                    b.HasIndex("MasterProfileId")
                        .HasDatabaseName("ix_qualification_requests_master_profile_id");

                    b.HasIndex("ResolverUserId")
                        .HasDatabaseName("ix_qualification_requests_resolver_user_id");

                    b.ToTable("qualification_requests", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientUserId")
                        .HasColumnType("integer")
                        .HasColumnName("client_user_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("MasterProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("master_profile_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int?>("WorkshopServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_service_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("ClientUserId")
                        .HasDatabaseName("ix_reviews_client_user_id");

                    b.HasIndex("MasterProfileId")
                        .HasDatabaseName("ix_reviews_master_profile_id");

                    b.HasIndex("WorkshopServiceId")
                        .HasDatabaseName("ix_reviews_workshop_service_id");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_review_target", "\"workshop_service_id\" IS NOT NULL OR \"master_profile_id\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("KLALIK.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_service_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_service_categories_name");

                    b.ToTable("service_categories", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.WorkshopService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionDirectionId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_direction_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageAssetPath")
                        .HasColumnType("text")
                        .HasColumnName("image_asset_path");

                    b.Property<bool>("IsHolidayRelated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_holiday_related");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("service_category_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_workshop_services");

                    b.HasIndex("CollectionDirectionId")
                        .HasDatabaseName("ix_workshop_services_collection_direction_id");

                    b.HasIndex("ServiceCategoryId")
                        .HasDatabaseName("ix_workshop_services_service_category_id");

                    b.ToTable("workshop_services", (string)null);
                });

            modelBuilder.Entity("KLALIK.Models.Entities.AppUser", b =>
                {
                    b.HasOne("KLALIK.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.BalanceTransaction", b =>
                {
                    b.HasOne("KLALIK.Models.Entities.AppUser", "User")
                        .WithMany("BalanceTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_balance_transactions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.Booking", b =>
                {
                    b.HasOne("KLALIK.Models.Entities.AppUser", "Client")
                        .WithMany("ClientBookings")
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_client_user_id");

                    b.HasOne("KLALIK.Models.Entities.MasterProfile", "MasterProfile")
                        .WithMany("Bookings")
                        .HasForeignKey("MasterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_master_profiles_master_profile_id");

                    b.HasOne("KLALIK.Models.Entities.WorkshopService", "WorkshopService")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkshopServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_workshop_services_workshop_service_id");

                    b.Navigation("Client");

                    b.Navigation("MasterProfile");

                    b.Navigation("WorkshopService");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.MasterProfile", b =>
                {
                    b.HasOne("KLALIK.Models.Entities.QualificationLevel", "QualificationLevel")
                        .WithMany("MasterProfiles")
                        .HasForeignKey("QualificationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_master_profiles_qualification_levels_qualification_level_id");

                    b.HasOne("KLALIK.Models.Entities.AppUser", "User")
                        .WithOne("MasterProfile")
                        .HasForeignKey("KLALIK.Models.Entities.MasterProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_master_profiles_users_user_id");

                    b.Navigation("QualificationLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.MasterServiceLink", b =>
                {
                    b.HasOne("KLALIK.Models.Entities.MasterProfile", "MasterProfile")
                        .WithMany("ServiceLinks")
                        .HasForeignKey("MasterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_master_service_links_master_profiles_master_profile_id");

                    b.HasOne("KLALIK.Models.Entities.WorkshopService", "WorkshopService")
                        .WithMany("MasterLinks")
                        .HasForeignKey("WorkshopServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_master_service_links_workshop_services_workshop_service_id");

                    b.Navigation("MasterProfile");

                    b.Navigation("WorkshopService");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.QualificationRequest", b =>
                {
                    b.HasOne("KLALIK.Models.Entities.MasterProfile", "MasterProfile")
                        .WithMany("QualificationRequests")
                        .HasForeignKey("MasterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qualification_requests_master_profiles_master_profile_id");

                    b.HasOne("KLALIK.Models.Entities.AppUser", "Resolver")
                        .WithMany("ResolvedQualificationRequests")
                        .HasForeignKey("ResolverUserId")
                        .HasConstraintName("fk_qualification_requests_users_resolver_user_id");

                    b.Navigation("MasterProfile");

                    b.Navigation("Resolver");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.Review", b =>
                {
                    b.HasOne("KLALIK.Models.Entities.AppUser", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_client_user_id");

                    b.HasOne("KLALIK.Models.Entities.MasterProfile", "MasterProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("MasterProfileId")
                        .HasConstraintName("fk_reviews_master_profiles_master_profile_id");

                    b.HasOne("KLALIK.Models.Entities.WorkshopService", "WorkshopService")
                        .WithMany("Reviews")
                        .HasForeignKey("WorkshopServiceId")
                        .HasConstraintName("fk_reviews_workshop_services_workshop_service_id");

                    b.Navigation("Client");

                    b.Navigation("MasterProfile");

                    b.Navigation("WorkshopService");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.WorkshopService", b =>
                {
                    b.HasOne("KLALIK.Models.Entities.CollectionDirection", "CollectionDirection")
                        .WithMany("Services")
                        .HasForeignKey("CollectionDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workshop_services_collection_directions_collection_directio");

                    b.HasOne("KLALIK.Models.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workshop_services_service_categories_service_category_id");

                    b.Navigation("CollectionDirection");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.AppUser", b =>
                {
                    b.Navigation("BalanceTransactions");

                    b.Navigation("ClientBookings");

                    b.Navigation("MasterProfile");

                    b.Navigation("ResolvedQualificationRequests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.CollectionDirection", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.MasterProfile", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("QualificationRequests");

                    b.Navigation("Reviews");

                    b.Navigation("ServiceLinks");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.QualificationLevel", b =>
                {
                    b.Navigation("MasterProfiles");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("KLALIK.Models.Entities.WorkshopService", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MasterLinks");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
